### ISSUE TITLE
is this for sale anywhere

### ISSUE THREAD

**Issue by dsssssssss9** [TOPGUNAki/grove-convert-module-for-dfplayermini#1]
Hi

Just what i've been looking for - is the product available to purchase anywhere i wonder?

Regards

**Comment by GomiHgy** [comment]
Hi
Thank you for your interest in this board.
Currently, it is only available at web stores in Japan.

If you want to pay by PayPal, I can handle it personally, how about it?

**Comment by dsssssssss9** [comment]
Hi sounds good 

not sure if this is the sort of thing that public issues on Github are for?  so i will , if ok with you, send you an email via the address in your profile?
